// This file will be auto-generated by GraphQL Code Generator
// Run: pnpm nx graphql-codegen @nyots/data-source

import { Injectable } from '@angular/core';
import { Query, gql } from 'apollo-angular';

// Placeholder types - will be replaced by codegen
export interface DashboardStats {
  totalUsers: number;
  totalProjects: number;
  totalContributions: number;
  totalRevenue: number;
  pendingContributions: number;
  pendingContributionsAmount: number;
  activeProjects: number;
  projectsByStatus: Array<{ status: string; count: number }>;
  contributionsByStatus: Array<{ status: string; count: number; amount: number }>;
}

export interface ContributionTrend {
  date: string;
  amount: number;
  count: number;
}

export interface TopProject {
  project: any;
  totalAmount: number;
  contributionCount: number;
}

export interface GetDashboardStatsQueryVariables {
  startDate?: Date;
  endDate?: Date;
}

export interface GetContributionTrendsQueryVariables {
  startDate: Date;
  endDate: Date;
  groupBy?: string;
}

export interface GetTopProjectsQueryVariables {
  limit?: number;
  startDate?: Date;
  endDate?: Date;
}

export interface GetRecentQueryVariables {
  limit?: number;
}

@Injectable({ providedIn: 'root' })
export class GetDashboardStatsGQL extends Query<
  { dashboardStats: DashboardStats },
  GetDashboardStatsQueryVariables
> {
  override document = gql`
    query GetDashboardStats($startDate: DateTime, $endDate: DateTime) {
      dashboardStats(startDate: $startDate, endDate: $endDate) {
        totalUsers
        totalProjects
        totalContributions
        totalRevenue
        pendingContributions
        pendingContributionsAmount
        activeProjects
        projectsByStatus {
          status
          count
        }
        contributionsByStatus {
          status
          count
          amount
        }
      }
    }
  `;
}

@Injectable({ providedIn: 'root' })
export class GetContributionTrendsGQL extends Query<
  { contributionTrends: ContributionTrend[] },
  GetContributionTrendsQueryVariables
> {
  override document = gql`
    query GetContributionTrends($startDate: DateTime!, $endDate: DateTime!, $groupBy: String) {
      contributionTrends(startDate: $startDate, endDate: $endDate, groupBy: $groupBy) {
        date
        amount
        count
      }
    }
  `;
}

@Injectable({ providedIn: 'root' })
export class GetTopProjectsGQL extends Query<
  { topProjects: TopProject[] },
  GetTopProjectsQueryVariables
> {
  override document = gql`
    query GetTopProjects($limit: Int, $startDate: DateTime, $endDate: DateTime) {
      topProjects(limit: $limit, startDate: $startDate, endDate: $endDate) {
        project {
          id
          title
          featuredImage
          status
        }
        totalAmount
        contributionCount
      }
    }
  `;
}

@Injectable({ providedIn: 'root' })
export class GetRecentContributionsGQL extends Query<any, GetRecentQueryVariables> {
  override document = gql`
    query GetRecentContributions($limit: Int) {
      getContributions(pagination: { first: $limit }) {
        edges {
          node {
            id
            amount
            paymentStatus
            createdAt
            user {
              id
              email
              firstName
              lastName
            }
            project {
              id
              title
            }
          }
        }
      }
    }
  `;
}

@Injectable({ providedIn: 'root' })
export class GetRecentProjectsGQL extends Query<any, GetRecentQueryVariables> {
  override document = gql`
    query GetRecentProjects($limit: Int) {
      getAllProjects(pagination: { first: $limit }) {
        edges {
          node {
            id
            title
            status
            goalAmount
            currentAmount
            createdAt
            category {
              id
              name
            }
          }
        }
      }
    }
  `;
}

@Injectable({ providedIn: 'root' })
export class GetRecentUsersGQL extends Query<any, GetRecentQueryVariables> {
  override document = gql`
    query GetRecentUsers($limit: Int) {
      getAllUsers(pagination: { first: $limit }) {
        edges {
          node {
            id
            email
            firstName
            lastName
            createdAt
          }
        }
      }
    }
  `;
}
