query GetAllCategories {
  getAllCategories {
    id
    name
    description
    projectCount
    createdAt
    updatedAt
  }
}

mutation CreateCategory($input: CreateCategoryInput!) {
  createCategory(input: $input) {
    id
    name
    description
    projectCount
    createdAt
    updatedAt
  }
}

mutation UpdateCategory($id: String!, $input: UpdateCategoryInput!) {
  updateCategory(id: $id, input: $input) {
    id
    name
    description
    projectCount
    createdAt
    updatedAt
  }
}

mutation DeleteCategory($id: String!) {
  deleteCategory(id: $id)
}
