name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.8.0
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: pnpm exec nx-cloud record -- echo Hello World
      - run: pnpm exec nx run-many -t docker:build --no-cloud

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Container Registry
        run: |
          docker tag apps-backend ghcr.io/${{ github.repository }}/apps-backend:latest
          docker push ghcr.io/${{ github.repository }}/apps-backend:latest
          docker tag apps-admin ghcr.io/${{ github.repository }}/apps-admin:latest
          docker push ghcr.io/${{ github.repository }}/apps-admin:latest
          docker tag apps-client ghcr.io/${{ github.repository }}/apps-client:latest
          docker push ghcr.io/${{ github.repository }}/apps-client:latest

      - name: Deploy to Contabo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.CONTABO_SERVER }}
          username: ${{ vars.CONTABO_USERNAME }}
          password: ${{ vars.CONTABO_PASSWORD }}
          script: |
            # Backend
            docker pull ghcr.io/${{ github.repository }}/apps-backend:latest
            docker stop apps-backend || true
            docker rm apps-backend || true
            docker run -d --name apps-backend -p 3000:3000 ghcr.io/${{ github.repository }}/apps-backend:latest

            # Admin
            docker pull ghcr.io/${{ github.repository }}/apps-admin:latest
            docker stop apps-admin || true
            docker rm apps-admin || true
            docker run -d --name apps-admin -p 51001:3000 ghcr.io/${{ github.repository }}/apps-admin:latest

            # Client
            docker pull ghcr.io/${{ github.repository }}/apps-client:latest
            docker stop apps-client || true
            docker rm apps-client || true
            docker run -d --name apps-client -p 51000:3000 ghcr.io/${{ github.repository }}/apps-client:latest

